
#include "uart.h"

ST_UART_LConfig_Type uart_lcfg_arr[NUM_Of_ID]=
{	
											/*ID_1_*/
	{UART_NORMAL_SPEED, NO_PARITY,ONE_STOP_BIT,	UART_8_BIT,UART_9600_BAUDRATE,UART_TX_RX_ENABLE},
											/*ID_2_*/
	{UART_NORMAL_SPEED, EVEN_PARITY,TWO_STOP_BIT,	UART_9_BIT,UART_38400_BAUDRATE,UART_RX_ENABLE},
											/*ID_3_*/
	{UART_DOUBLE_SPEED, ODD_PARITY,ONE_STOP_BIT,UART_7_BIT,UART_2400_BAUDRATE,UART_TX_ENABLE},
 };
												 
												 